name: webstn
services:

  activemq-classic:
    image: apache/activemq-classic:5.18.6
    restart: always
    container_name: activemq-classic-cnr
    ports:
      - 61616:61616
      - 8161:8161

#  activemq-classic:
#      container_name: activemq-classic-cnr
#      ports:
#        - 61616:61616
#        - 8161:8161
#     image: apache/activemq-classic:latest

#  mysql:
#    container_name: mysql-cnr
#    restart: always
#    ports:
#      - 3306:3306
#    environment:
#      - MYSQL_ROOT_PASSWORD=lera
#      - MYSQL_DATABASE=aero
#    image: mysql:lts

  webstn:
      image: webstn-21-img:v0.1
      restart: always
      container_name: webstn-v01-cnr
      ports:
        - 80:80
      depends_on:
        - activemq-classic
 #      - mysql