name: scanner
services:

  activemq-classic:
      image: apache/activemq-classic:5.18.6
      restart: always
      container_name: activemq-classic-cnr
      ports:
        - 61616:61616
        - 8161:8161

  scanner:
      image: scanner-21-img:v0.1
      restart: always
      container_name: scanner-v1-cnr
      ports:
          - 81:81