services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=pg-advisor-db'
      - 'POSTGRES_PASSWORD=advisor'
      - 'POSTGRES_USER=advisor'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    container_name: pgvector-db-cnr
    ports:
      - '5432:5432'
#    volumes:
#      - ./postgres-ig-volume:/var/lib/ig_pgvector/data

#  chat-bot-ai:
##      build: .
#      image: igr025/chat-bot-ai-21-img:v0.1
#      container_name: chat-bot-ai-cnr
#      ports:
#        - 88:88
#      environment:
#        db-url: jdbc:postgresql://pgvector-db-cnr:5432/pg-advisor-db
#        db-username: advisor
#        db-password: advisor
#      depends_on:
#          - pgvector
#      restart: always

  pgadmin:
      image: dpage/pgadmin4:latest
      environment:
          - 'PGADMIN_DEFAULT_EMAIL=admin@admin.admin'
          - 'PGADMIN_DEFAULT_PASSWORD=admin'
      restart: always
      container_name: pgadmin-cnr
      ports:
        - 8081:80
      depends_on:
        - pgvector